name: Mirror to Personal Repository
on:
  push:
    branches:
      - main
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
      - name: Debug Git
        run: |
          echo "Git remotes"
          git remote -v
          echo "Branches"
          git branch -a
      - name: Push to Mirror
        run: |
          git remote add mirror https://x-access-token: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@github.com/derickddo/kleankickx-backend.git
          git push mirror main --force